# Generated by Django 4.2.4 on 2024-02-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='rating',
            field=models.CharField(choices=[('⭐⭐⭐⭐⭐', '5'), ('⭐', '1'), ('⭐⭐', '2'), ('⭐⭐⭐', '3'), ('⭐⭐⭐⭐', '4')], max_length=20),
        ),
    ]
