# Generated by Django 4.2.4 on 2024-02-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_reviewmodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='rating',
            field=models.CharField(choices=[('⭐⭐', '2'), ('⭐⭐⭐⭐⭐', '5'), ('⭐⭐⭐', '3'), ('⭐⭐⭐⭐', '4'), ('⭐', '1')], max_length=20),
        ),
    ]
