# Generated by Django 4.2.4 on 2024-02-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_reviewmodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='rating',
            field=models.CharField(choices=[('⭐⭐⭐⭐', '4'), ('⭐', '1'), ('⭐⭐⭐⭐⭐', '5'), ('⭐⭐', '2'), ('⭐⭐⭐', '3')], max_length=20),
        ),
    ]
