# Generated by Django 4.2.4 on 2024-02-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_reviewmodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='rating',
            field=models.CharField(choices=[('⭐⭐⭐', '3'), ('⭐⭐⭐⭐⭐', '5'), ('⭐⭐', '2'), ('⭐', '1'), ('⭐⭐⭐⭐', '4')], max_length=20),
        ),
    ]
