# Generated by Django 4.2.4 on 2024-02-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='role',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], max_length=30),
        ),
    ]
